<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2L70A79" failures="1" tests="4" name="Test" time="49.094" errors="0" timestamp="2024-10-16T16:56:28 IST">
  <testcase classname="vtigerTests.CreateContactTest" name="createContactWithOrgTest" time="7.9"/>
  <testcase classname="vtigerTests.CreateAndDuplicateLeadTest" name="createLeadTest" time="8.263"/>
  <testcase classname="vtigerTests.CreateOrganizationTest" name="createOrgTest" time="7.365">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Creati New Organization] but found [Creating New Organization]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Creati New Organization] but found [Creating New Organization]
at vtigerTests.CreateOrganizationTest.createOrgTest(CreateOrganizationTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createOrgTest -->
  <testcase classname="vtigerTests.CreateEventTest" name="createEventTest" time="3.907"/>
</testsuite> <!-- Test -->
